### ISSUE TITLE
Error callback not working on Safari 9.0.2

### ISSUE THREAD

**Issue by Cisplatin** [omichelsen/clipboard-button#1]
The following snippet of code:

``` Javascript
function success_cpy() {    
    $('#roomLink').attr('data-content', 'Copied!');    
};    

function fail_cpy(err) {    
    $('#roomLink').attr('data-content', 'Press ⌘ C to copy!');    
};    

var cpb = clipboardButton('#roomLink', success_cpy, fail_cpy);    
$(roomLink).attr("data-clipboard-text", window.location.href);  
```

Will execute "success_cpy" on Safari 9.0.2 even though it's a failed copy (when roomLink is clicked). Should it not be calling "fail_cpy" instead?

**Comment by omichelsen** [comment]
True, this is because Safari is not supported, but fails silently. I am working on adding feature detection to support this.

**Comment by omichelsen** [comment]
In v1.1.0 I have added a new static property `clipboardButton.supported` which you can use to detect browser support.
